# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# MAJOR, API, MINOR
mod_version=1.0.5
mc_version=1.20.1
forge_version=47.3.0
jei_version=6075247
crust_api_version=6403332
crust_src_version=6403339
tc_version=6266282
mantle_version=6258424