# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# MAJOR, API, MINOR
mod_version=1.0.5
mc_version=1.20.1

# Deps and tools
forge_version=47.4.0

jei_version=6600311

crust_api_version=7230959
crust_src_version=7230962

tc_version=6777068
mantle_version=6819217

#colorfh_version=5724977
#colorfh_src_version=5724978