modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/FatherToast/NaturalAbsorption/issues/"

[[mods]]
logoFile = "banner.png"
authors = "Father Toast"
credits = "Sarinsa (big brain), Tutta (textures), Mother Toast & Baby Toast"
version = "${file.jarVersion}"
displayName = "Natural Absorption"
modId = "naturalabsorption"
description = '''
Puts the vanilla mechanic 'absorption' to use as a regenerating health buffer, complete with an enchantment and upgrade system.
Additionally adds options to disable and/or limit health regeneration and armor. Disables health regen by default.

This mod is highly configurable and each feature has at least one config option associated with it.
Browsing the configs will provide information on all the mod's features. If more in-depth information is needed, ask in the Discord server.

Download: https://www.curseforge.com/members/fathertoast/projects/

Source: https://github.com/FatherToast/

Discussion: https://discord.gg/GFTzTdX

Sarinsa's Discord: https://discord.gg/8FhRDZGAvX
'''

[[dependencies.naturalabsorption]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.naturalabsorption]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.naturalabsorption]]
modId = "tconstruct"
mandatory = false
versionRange = "[3.5.1.31,)"
ordering = "BEFORE"
side = "BOTH"