@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.naturalabsorption.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;