@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.naturalabsorption.api.impl;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;