@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.naturalabsorption.common.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;