@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.naturalabsorption.common.core.hearts;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;