@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.naturalabsorption.common.core.register;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;