@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.naturalabsorption.common.compat.tc;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;